In [1]:
# 택스트 전처리 함수 text_to_sequence() 호출
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [2]:
# 전처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'

In [3]:
# 해당 텍스트 토큰화
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
# 텍스트 전처리 함수 Tokenizer() 호출
from keras.preprocessing.text import Tokenizer

In [5]:
# 전처리하려는 세 개의 문장 정하기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [6]:
# 토큰화 함수를 이용해 전처리하는 과정
token = Tokenizer()       # 토큰화 함수 지정
token.fit_on_texts(docs)  # 토큰화 함수에 문장 적용하기

In [7]:
# 각 옵션에 맞춰 단어 빈도 수를 계산한 결과 출력
print("\n단어 카운트:\n", token.word_counts)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 2), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [8]:
# 출력되는 순서는 랜덤
print("\n문장 카운트: ", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값:\n", token.word_index)


문장 카운트:  3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'단어를': 1, '토큰화': 2, '텍스트의': 2, '나누어': 1, '합니다': 1, '각': 1, '먼저': 1, '딥러닝에서': 2, '인식됩니다': 1, '단어로': 1, '해야': 1, '사용할': 1, '결과는': 1, '토큰화한': 1, '수': 1, '있습니다': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


### 단어의 원-핫 인코딩

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [10]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [11]:
from keras.utils import to_categorical

# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes  = word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


### 텍스트를 읽고 긍정, 부정 예측하기

In [12]:
import numpy as np
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

In [13]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.', '한번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

In [14]:
# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [15]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [17]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [18]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞춤
padded_x = pad_sequences(x, 4)
print("\n패딩 결과\n", padded_x)


패딩 결과
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [19]:
# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index) + 1

In [20]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [22]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 0.6970 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6948 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6927 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6905 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6883 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6862 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6840 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6819 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6797 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6776 - accuracy: 0.9000
Epoch 11/20
1/1 [=======================

In [23]:
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 342ms/step - loss: 0.6536 - accuracy: 0.9000

 Accuracy: 0.9000
